name: sciT_snakemake_1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip=25.1.1
  - samtools=1.20
  - p7zip=16.02
  - gcc=13.2.0
  - libzlib
  - openjdk=23.0.2
  - snakemake-executor-plugin-slurm=1.2.1
  - snakemake-executor-plugin-slurm-jobstep=0.3.0
  - libmamba=2.1.1=h430c389_0
  - mamba=2.1.1=had4a41a_0
  - zstd=1.5.6
  - setuptools=80.1.0
  - libxml2=2.13.7
  - pip:
      - anndata==0.10.7
      - annotated-types==0.7.0
      - array-api-compat==1.6
      - biopython==1.83
      - cached-property==1.5.2
      - click==8.1.7
      - coloredlogs==15.0.1
      - colormath==3.0.0
      - contourpy==1.2.1
      - cutadapt==4.8
      - cycler==0.12.1
      - dnaio==1.2.0
      - fonttools==4.51.0
      - h5py==3.11.0
      - humanize==4.9.0
      - importlib-metadata==7.1.0
      - isal==1.6.1
      - joblib==1.4.2
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - llvmlite==0.42.0
      - logomaker==0.8.7
      - loompy==3.0.7
      - lxml==5.2.2
      - markdown==3.6
      - matplotlib==3.9.0
      - more-itertools==10.2.0
      - natsort==8.4.0
      - networkx==3.3
      - numba==0.59.1
      - numpy-groupies==0.11.1
      - patsy==0.5.6
      - pillow==10.3.0
      - plotext==5.2.8
      - plotly==5.22.0
      - pyaml-env==1.2.1
      - pybigwig==0.3.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pysam==0.22.1
      - pysamiterators==1.9
      - pytest-runner==6.0.1
      - rich-click==1.8.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - spectra==0.0.11
      - statsmodels==0.14.2
      - tenacity==8.3.0
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - typeguard==4.4.2
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - xopen==2.0.1
      - zlib-ng==0.4.3
